user:
  email:
    max_length: 255
  name:
    max_length: 50
  password:
    min_length: 6
  limit_page: 5
  password_reset_expired:
    time_reset: 2
  microposts_limit: 5
  following:
    limit: 5
  follower:
    limit: 5
users_helper:
  gravatar_size: 80
micropost:
  content:
    max_length: 140
static_pages:
  home:
    feed_item_limit: 5
